name: DAST Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  dast_scan:
    name: OWASP ZAP DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run OWASP ZAP DAST Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: 'http://www.itsecgames.com/'

      - name: Generate ZAP Report
        run: |
          docker run --rm -v ${PWD}:/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t http://www.itsecgames.com/ -r zap-report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap-report.html
